### ISSUE TITLE
(some) temp and (all)fans report as zero on latest arch kernel

### ISSUE THREAD

**Issue by zany130** [MisterZ42/corsair-cpro#3] opened 2022-05-04 01:50 UTC
on 
`Linux Kiseki 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux`

`sudo sensors` reports
```
corsaircpro-hid-3-a
Adapter: HID adapter
in0:           0.00 V
in1:              N/A
in2:           0.00 V
fan1 3pin:      0 RPM
fan2 3pin:      0 RPM
fan3 3pin:      0 RPM
fan4 4pin:      0 RPM
fan5 4pin:      0 RPM
temp1:            N/A
temp2:        +26.6°C
temp3:        +27.2°C
temp4:        +29.4°C

zenpower-pci-00c3
Adapter: PCI adapter
SVI2_Core:     1.40 V
SVI2_SoC:      1.09 V
Tdie:         +44.5°C  (high = +95.0°C)
Tctl:         +44.5°C
SVI2_P_Core:  56.74 W
SVI2_P_SoC:   18.84 W
SVI2_C_Core:  40.53 A
SVI2_C_SoC:   17.32 A

nvme-pci-0100
Adapter: PCI adapter
Composite:    +37.9°C  (low  = -273.1°C, high = +83.8°C)
                       (crit = +83.8°C)
Sensor 1:     +37.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +37.9°C  (low  = -273.1°C, high = +65261.8°C)

nct6779-isa-0290
Adapter: ISA adapter
Vcore:                 704.00 mV (min =  +0.00 V, max =  +1.74 V)
in1:                     1.28 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
AVCC:                    3.26 V  (min =  +2.98 V, max =  +3.63 V)
+3.3V:                   3.26 V  (min =  +2.98 V, max =  +3.63 V)
in4:                     1.82 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                     1.10 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                     1.36 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
3VSB:                    3.41 V  (min =  +2.98 V, max =  +3.63 V)
Vbat:                    3.28 V  (min =  +2.70 V, max =  +3.63 V)
in9:                     0.00 V  (min =  +0.00 V, max =  +0.00 V)
in10:                  704.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                    1.07 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                    1.64 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                  928.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                    1.84 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                     0 RPM  (min =    0 RPM)
fan2:                  1804 RPM  (min =    0 RPM)
fan3:                     0 RPM  (min =    0 RPM)
fan4:                     0 RPM  (min =    0 RPM)
fan5:                     0 RPM  (min =    0 RPM)
SYSTIN:                 +36.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = thermistor
CPUTIN:                 +39.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
AUXTIN0:                 +7.0°C    sensor = thermistor
AUXTIN1:                +43.0°C    sensor = thermistor
AUXTIN2:                +22.0°C    sensor = thermistor
AUXTIN3:                -27.0°C    sensor = thermistor
SMBUSMASTER 0:          +44.5°C
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C
PCH_CHIP_TEMP:           +0.0°C
PCH_CPU_TEMP:            +0.0°C
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled

nvme-pci-0b00
Adapter: PCI adapter
Composite:    +35.9°C  (low  = -273.1°C, high = +81.8°C)
                       (crit = +84.8°C)
Sensor 1:     +35.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +43.9°C  (low  = -273.1°C, high = +65261.8°C)
```
on the latest lts kernel `5.15.37-1`

it shows the correct temps and fan speeds

more sys info 

```
inxi -b
System:
  Host: Kiseki Kernel: 5.17.5-arch1-1 arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.5 Distro: Garuda Linux
Machine:
  Type: Desktop Mobo: ASRock model: X470 Taichi serial: <superuser required>
    UEFI: American Megatrends v: P4.86 date: 01/27/2022
CPU:
  Info: 6-core AMD Ryzen 5 2600X [MT MCP] speed (MHz): avg: 4109
    min/max: 2200/3600
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1080] driver: nvidia v: 510.68.02
  Display: x11 server: X.Org v: 21.1.3 with: Xwayland v: 22.1.1 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1: 2560x1080
    2: 3840x2160~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.68.02
Network:
  Device-1: Intel I211 Gigabit Network driver: igb
Drives:
  Local Storage: total: 2.96 TiB used: 2.99 TiB (101.2%)
Info:
  Processes: 457 Uptime: 10m Memory: 31.27 GiB used: 12.95 GiB (41.4%)
  Shell: fish inxi: 3.3.15
  ```

**Comment by MisterZ42** [comment] 2022-05-04 06:30
Hi
Can you give me the output of "dmesg | grep -i corsair"?
Are the fan types (3pin/4pin) detected correctly?
Does sensors need more time than before while showing the numbers?
What happens if you try to reload the driver? ("sudo modprobe -r corsair-cpro && sudo modprobe corsair-cpro" and then look at dmesg)
Did you check with a user space driver (e. g. liquidctl) if it also returns zeros?
Thanks.

**Comment by zany130** [comment] 2022-05-04 16:12
sure 

**dmesg**
___
```
sudo dmesg | grep -i corsair
[    7.841449] usb 1-14: Manufacturer: Corsair
[    7.869823] hid-generic 0003:1B1C:0C10.000A: hiddev99,hidraw7: USB HID v1.11 Device [Corsair Commander PRO] on usb-0000:02:00.0-14/input0
[    7.904639] corsair-cpro 0003:1B1C:0C10.000A: hidraw7: USB HID v1.11 Device [Corsair Commander PRO] on usb-0000:02:00.0-14/input0
```
___

**fan pins**
___
as you can see here 
```
sensors
corsaircpro-hid-3-a
Adapter: HID adapter
in0:           0.00 V
in1:              N/A
in2:           0.00 V
fan1 3pin:        N/A
fan2 3pin:      0 RPM
fan3 3pin:        N/A
fan4 4pin:      0 RPM
fan5 4pin:        N/A
temp1:         +0.0°C
temp2:            N/A
temp3:         +0.0°C
temp4:         +0.0°C
```
it detects the first 3 fans as 3pin and the last 2 as 4pin this is correct

**do the sensors need more time?**
___
not sure how would I test that
___

**module reload**
___
as you can see here
```
sudo modprobe -r corsair-cpro && sudo modprobe corsair-cpro

💡 please => sudo

 ╭─zany130@Kiseki in ~ as 🧙 took 155ms
 ╰─λ sudo dmesg | grep -i corsair
[    7.841449] usb 1-14: Manufacturer: Corsair
[    7.869823] hid-generic 0003:1B1C:0C10.000A: hiddev99,hidraw7: USB HID v1.11 Device [Corsair Commander PRO] on usb-0000:02:00.0-14/input0
[    7.904639] corsair-cpro 0003:1B1C:0C10.000A: hidraw7: USB HID v1.11 Device [Corsair Commander PRO] on usb-0000:02:00.0-14/input0
[ 3277.538302] hid-generic 0003:1B1C:0C10.000A: hiddev99,hidraw8: USB HID v1.11 Device [Corsair Commander PRO] on usb-0000:02:00.0-14/input0
[ 3277.619524] corsair-cpro 0003:1B1C:0C10.000A: hidraw9: USB HID v1.11 Device [Corsair Commander PRO] on usb-0000:02:00.0-14/input0

💡 please => sudo

 ╭─zany130@Kiseki in ~ as 🧙 took 15ms
 ╰─λ sensors
corsaircpro-hid-3-a
Adapter: HID adapter
in0:          11.98 V
in1:           4.92 V
in2:           3.37 V
fan1 3pin:   1294 RPM
fan2 3pin:   1287 RPM
fan3 3pin:   1311 RPM
fan4 4pin:   1572 RPM
fan5 4pin:   1214 RPM
temp1:        +26.0°C
temp2:        +26.6°C
temp3:        +29.0°C
temp4:        +28.3°C
```
that does indeed resolve the issue
___

**Did you check with a user space driver (e. g. liquidctl) if it also returns zeros?**
___
no will check that out and report back
___


EDIT: seems to be a conflict with openrgb i noticed my rgb lights where not working after the module reload so I closed and reopened openrgb and noticed all the sensors went back to 0
```
corsaircpro-hid-3-a
Adapter: HID adapter
in0:           0.00 V
in1:              N/A
in2:           0.00 V
fan1 3pin:      0 RPM
fan2 3pin:      0 RPM
fan3 3pin:      0 RPM
fan4 4pin:      0 RPM
fan5 4pin:      0 RPM
temp1:            N/A
temp2:        +25.3°C
temp3:        +26.0°C
temp4:        +28.2°C
```

What is strange is this dosn't happen on a lts kernel.

**Comment by MisterZ42** [comment] 2022-05-04 22:22
I am trying to somehow reproduce this on the same kernel, but I am not able to. (on arch)
So here are a few ideas:

1. If you run sensors multiple times, is the missing data always the same or does it change?

2. Can you tell me, what Version of OpenRGB you are using? (pacman -Q openrgb)
Can you tell me what it says in OpenRGB -> Information -> Corsair Commander Pro -> Version and Location.

3. Maybe try "dmesg --follow" and watch the output while closing OpenRGB, reloading the driver and reopening OpenRGB. Look out for any hidraw / hid / usb messages. I am a bit confused, because in your log the hidraw number changes, which it should not do and could be connected to this problem.
Also post the udev-rule for openrgb. On my system I can see it with "cat /usr/lib/udev/rules.d/60-openrgb.rules | grep 0c10"

4. Try to do the same while looking at "udevadm monitor" and send me the output.

Hoping there will be a hint somewhere.

**Comment by zany130** [comment] 2022-05-04 22:37
1. each time I run the fans always report 0 RPM but which temps show N/A changes

2. right now Im using `openrgb-git r2388.1f3415bd-1` but the same thing was happening on `0.7-5` 

3.  here are my rules 
```
cat /usr/lib/udev/rules.d/60-openrgb.rules | grep 0c10
SUBSYSTEMS=="usb|hidraw", ATTRS{idVendor}=="1b1c", ATTRS{idProduct}=="0c10", TAG+="uaccess", TAG+="Corsair_Commander_Pro"
```
also here is the output of dmesg -follow
as a haste bin since it was pretty long 
https://hastebin.skyra.pw/tosoqebaka.yaml

4. `udevadm monitor` didn't show anything don't know if if its because I was supposed to use sudo

```
 sudo udevadm monitor
[sudo] password for zany130:
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent
```

**Comment by MisterZ42** [comment] 2022-05-04 22:51
Both outputs (dmesg --follow and udevadm monitor) are meant to be running while you unload/reload the driver and restart openrgb.
Can you tell me what it says in OpenRGB -> Information -> Corsair Commander Pro -> Version and Location.
Also the output of "grep 0c10 /usr/lib/udev/rules.d/*" and "grep 0c10 /etc/udev/rules.d/*" could be interesting.

**Comment by zany130** [comment] 2022-05-04 23:40
here is the dmesg log (started with openrgb already open but before I ran the command to reload the module ) https://hastebin.skyra.pw/iculajuhim.yaml
here is the `udevadm monitor`
```
] password for zany130:
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[4246.918559] remove   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hwmon/hwmon4 (hwmon)
KERNEL[4246.918728] remove   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hidraw/hidraw7 (hidraw)
KERNEL[4246.918748] unbind   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A (hid)
KERNEL[4246.918761] remove   /bus/hid/drivers/corsair-cpro (drivers)
KERNEL[4246.919036] add      /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/usbmisc/hiddev3 (usbmisc)
KERNEL[4246.919076] add      /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hidraw/hidraw9 (hidraw)
KERNEL[4246.919120] bind     /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A (hid)
KERNEL[4246.919901] remove   /module/corsair_cpro (module)
UDEV  [4246.921188] remove   /bus/hid/drivers/corsair-cpro (drivers)
UDEV  [4246.921630] remove   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hwmon/hwmon4 (hwmon)
UDEV  [4246.921999] remove   /module/corsair_cpro (module)
UDEV  [4246.922393] remove   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hidraw/hidraw7 (hidraw)
UDEV  [4246.923515] add      /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/usbmisc/hiddev3 (usbmisc)
UDEV  [4246.924391] unbind   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A (hid)
UDEV  [4246.937578] add      /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hidraw/hidraw9 (hidraw)
UDEV  [4246.939156] bind     /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A (hid)
KERNEL[4246.950528] add      /bus/hid/drivers/corsair-cpro (drivers)
KERNEL[4246.950589] remove   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/usbmisc/hiddev3 (usbmisc)
UDEV  [4246.951476] add      /bus/hid/drivers/corsair-cpro (drivers)
UDEV  [4246.952118] remove   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/usbmisc/hiddev3 (usbmisc)
KERNEL[4246.990602] remove   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hidraw/hidraw9 (hidraw)
KERNEL[4246.990632] unbind   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A (hid)
KERNEL[4246.992443] add      /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hidraw/hidraw10 (hidraw)
UDEV  [4246.992482] remove   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hidraw/hidraw9 (hidraw)
UDEV  [4246.993983] unbind   /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A (hid)
UDEV  [4246.999761] add      /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hidraw/hidraw10 (hidraw)
KERNEL[4247.048697] add      /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hwmon/hwmon4 (hwmon)
KERNEL[4247.048725] bind     /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A (hid)
KERNEL[4247.048738] add      /module/corsair_cpro (module)
UDEV  [4247.049751] add      /module/corsair_cpro (module)
UDEV  [4247.050723] add      /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A/hwmon/hwmon4 (hwmon)
UDEV  [4247.052180] bind     /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-14/1-14:1.0/0003:1B1C:0C10.000A (hid)
```
as for the `greps` I am confused what you mean. if you mean the openrgb rule file I provided that above

as for the device info from openrgb 
`openrgb -l` shows 
```
Corsair Commander Pro
  Type:           LED Strip
  Description:    Corsair Lighting Node Device
  Version:        0.0.0
  Location:       HID: /dev/hidraw10
  Serial:         0E0500637329041A
  Modes: [Direct] 'Rainbow Wave' 'Color Shift' 'Color Pulse' 'Color Wave' Static Temperature Visor Marquee Blink Sequential Rainbow
  Zones: 'Corsair Channel 1' 'Corsair Channel 2'
  ```
that's the same thing it says in the GUI although for some reason on the GUI it says the version is `0.9.212`

EDIT: Thought I should clarify in case you notice that I'm using a custom kernel when I got this dmesg (and the last one too)  I normally use the tkg kernel but I tried the vanilla arch kernel to make sure it wasn't something only in the tkg kernel. It happens on both though, so I switched back to use the tkg kernel.

**Comment by MisterZ42** [comment] 2022-05-05 11:37
I am still at a loss what is happening. `openrgb -l` should show the correct firmware version in the command line output. Why it shows 0.0.0 but works in the GUI could have the same cause. I am guessing it has to do with hidraw and/or udev but I am really not sure.
Do you have any other program which could access hidraw devices? There could be some conflict there.
You can check with `lsof /dev/hidrawX` where X is the number shown in dmesg or openrgb. (Try out the different ones, which are shown in `dmesg | grep -i corsair`) This will show, which process has a handle on a specific file.

Sorry the asterisk went missing it should read like this:
`grep 0c10 /usr/lib/udev/rules.d/*` and `grep 0c10 /etc/udev/rules.d/*`
This will search all udev-rules for 0c10 (which is the id of the device) Maybe there is something unusual there?

Edit:
Could you repost the kernel log (dmesg). It seems to have been removed from hastebin.

**Comment by zany130** [comment] 2022-05-05 13:09
hmm this is intresting,,,
```
lsof /dev/hidraw7
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
openrgb 4862 zany130   15u   CHR  239,7      0t0 1026 /dev/hidraw7
heroic  4940 zany130  110u   CHR  239,7      0t0 1026 /dev/hidraw7
```
why is[heroic](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher) accessing the commander pro?

also here is the grep commands 
```
grep 0c10 /usr/lib/udev/rules.d/*
/usr/lib/udev/rules.d/60-openrgb.rules:SUBSYSTEMS=="usb|hidraw", ATTRS{idVendor}=="1b1c", ATTRS{idProduct}=="0c10", TAG+="uaccess", TAG+="Corsair_Commander_Pro"

 ╭─zany130@Kiseki in ~ as 🧙 took 3ms
 ╰─λ grep 0c10 /etc/udev/rules.d/*
 ```
 here is the dmesg also https://hastebin.skyra.pw/awacufefev.yaml
 
 EDIT: Disabling heroic launcher from starting at startup and then rebooting doesn't fix the issue though unfortunately so there is something more going on
 
 EDIT2: BTW this is how the output looks now
 ```
 lsof /dev/hidraw7
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
openrgb 4553 zany130   15u   CHR  239,7      0t0 1017 /dev/hidraw7
```

Next, since I think you said openrgb and sensors work for you together I'm going to try disabling the [effects plugin](https://gitlab.com/OpenRGBDevelopers/OpenRGBEffectsPlugin) I am using

**Comment by zany130** [comment] 2022-05-05 13:27
so disabling the effects plugin did the trick. `sensors` now report the correct temps and fan speeds

```
sudo sensors
corsaircpro-hid-3-a
Adapter: HID adapter
in0:          11.90 V
in1:           4.76 V
in2:           3.31 V
fan1 3pin:   1286 RPM
fan2 3pin:   1277 RPM
fan3 3pin:   1301 RPM
fan4 4pin:   1566 RPM
fan5 4pin:   1209 RPM
temp1:        +26.6°C
temp2:        +27.1°C
temp3:        +28.1°C
temp4:        +29.0°C

zenpower-pci-00c3
Adapter: PCI adapter
SVI2_Core:     1.39 V
SVI2_SoC:      1.09 V
Tdie:         +49.0°C  (high = +95.0°C)
Tctl:         +49.0°C
SVI2_P_Core:  70.98 W
SVI2_P_SoC:   18.94 W
SVI2_C_Core:  57.16 A
SVI2_C_SoC:   16.96 A

nvme-pci-0100
Adapter: PCI adapter
Composite:    +35.9°C  (low  = -273.1°C, high = +83.8°C)
                       (crit = +83.8°C)
Sensor 1:     +35.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +36.9°C  (low  = -273.1°C, high = +65261.8°C)

nct6779-isa-0290
Adapter: ISA adapter
Vcore:                 704.00 mV (min =  +0.00 V, max =  +1.74 V)
in1:                     1.28 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
AVCC:                    3.25 V  (min =  +2.98 V, max =  +3.63 V)
+3.3V:                   3.25 V  (min =  +2.98 V, max =  +3.63 V)
in4:                     1.82 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                     1.10 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                     1.36 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
3VSB:                    3.41 V  (min =  +2.98 V, max =  +3.63 V)
Vbat:                    3.28 V  (min =  +2.70 V, max =  +3.63 V)
in9:                     0.00 V  (min =  +0.00 V, max =  +0.00 V)
in10:                  720.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                    1.07 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                    1.63 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                  928.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                    1.84 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                     0 RPM  (min =    0 RPM)
fan2:                  2039 RPM  (min =    0 RPM)
fan3:                     0 RPM  (min =    0 RPM)
fan4:                     0 RPM  (min =    0 RPM)
fan5:                     0 RPM  (min =    0 RPM)
SYSTIN:                 +35.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = thermistor
CPUTIN:                 +40.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
AUXTIN0:                 +7.0°C    sensor = thermistor
AUXTIN1:                +42.0°C    sensor = thermistor
AUXTIN2:                +22.0°C    sensor = thermistor
AUXTIN3:                -27.0°C    sensor = thermistor
SMBUSMASTER 0:          +49.0°C
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C
PCH_CHIP_TEMP:           +0.0°C
PCH_CPU_TEMP:            +0.0°C
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled

nvme-pci-0b00
Adapter: PCI adapter
Composite:    +41.9°C  (low  = -273.1°C, high = +81.8°C)
                       (crit = +84.8°C)
Sensor 1:     +41.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +55.9°C  (low  = -273.1°C, high = +65261.8°C)


💡 please => sudo

 ╭─zany130@Kiseki in ~ as 🧙 took 76ms
 ╰─λ lsof /dev/hidraw7
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
openrgb 4580 zany130   15u   CHR  239,7      0t0 1018 /dev/hidraw7
```

**Comment by MisterZ42** [comment] 2022-05-05 13:48
Ok. I tested it and can reproduce the problem. Because the effects plugin makes very many calls to the device per second, it interferes with the kernel driver. And because of how this device is designed it is not possible to separate, where the requests are coming from.
For now you could try to use less FPS in the effects plugin, but readings from the driver may be inconsistent. Maybe there will be a solution in the future, but this I cannot promise.

**Comment by MisterZ42** [comment] 2022-05-05 16:13
Anyway, I had a bit of time to try to hack a dirty fix into the driver. In this form it can not be in the kernel, but if you want to try it, I put it in the "hidraw-hack" branch. If you want to compile it, it might solve your problem for the moment.

**Comment by zany130** [comment] 2022-05-06 17:29
yup works with the `hidraw-hack` branch

only problem I have is `pwmconfig` is still not creating the correct `fancontrol` config file for the fans attached to the hub but this might be an issue elsewhere and not with the driver since its reporting the fan speeds and temps

```
sudo pwmconfig
# pwmconfig version 3.6.0+git
This program will search your sensors for pulse width modulation (pwm)
controls, and test each one to see if it controls a fan on
your motherboard. Note that many motherboards do not have pwm
circuitry installed, even if your sensor chip supports pwm.

We will attempt to briefly stop each fan using the pwm controls.
The program will attempt to restore each fan to full speed
after testing. However, it is ** very important ** that you
physically verify that the fans have been to full speed
after the program has completed.

Found the following devices:
   hwmon0 is nvme
   hwmon1 is nvme
   hwmon2 is zenpower
   hwmon3 is nct6779
   hwmon4 is corsaircpro
   hwmon5 is hidpp_battery_0

Found the following PWM controls:
   hwmon3/pwm1           current value: 127
hwmon3/pwm1 is currently setup for automatic speed control.
In general, automatic mode is preferred over manual mode, as
it is more efficient and it reacts faster. Are you sure that
you want to setup this output for manual control? (n)
   hwmon3/pwm2           current value: 142
hwmon3/pwm2 is currently setup for automatic speed control.
In general, automatic mode is preferred over manual mode, as
it is more efficient and it reacts faster. Are you sure that
you want to setup this output for manual control? (n)
   hwmon3/pwm3           current value: 142
hwmon3/pwm3 is currently setup for automatic speed control.
In general, automatic mode is preferred over manual mode, as
it is more efficient and it reacts faster. Are you sure that
you want to setup this output for manual control? (n)
   hwmon3/pwm4           current value: 127
hwmon3/pwm4 is currently setup for automatic speed control.
In general, automatic mode is preferred over manual mode, as
it is more efficient and it reacts faster. Are you sure that
you want to setup this output for manual control? (n)
   hwmon3/pwm5           current value: 0
hwmon3/pwm5 is currently setup for automatic speed control.
In general, automatic mode is preferred over manual mode, as
it is more efficient and it reacts faster. Are you sure that
you want to setup this output for manual control? (n)
   hwmon4/pwm1           current value: 255
   hwmon4/pwm2           current value: 255
   hwmon4/pwm3           current value: 255
   hwmon4/pwm4           current value: 255
   hwmon4/pwm5           current value: 255

Giving the fans some time to reach full speed...
Found the following fan sensors:
   hwmon3/fan1_input     current speed: 0 ... skipping!
   hwmon3/fan2_input     current speed: 1719 RPM
   hwmon3/fan3_input     current speed: 0 ... skipping!
   hwmon3/fan4_input     current speed: 0 ... skipping!
   hwmon3/fan5_input     current speed: 0 ... skipping!
   hwmon4/fan1_input     current speed: 1298 RPM
   hwmon4/fan2_input     current speed: 1286 RPM
   hwmon4/fan3_input     current speed: 1311 RPM
   hwmon4/fan4_input     current speed: 1568 RPM
   hwmon4/fan5_input     current speed: 1216 RPM

Warning!!! This program will stop your fans, one at a time,
for approximately 5 seconds each!!!
This may cause your processor temperature to rise!!!
If you do not want to do this hit control-C now!!!
Hit return to continue:

Testing pwm control hwmon4/pwm1 ...
  hwmon3/fan2_input ... speed was 1719 now 1814
    no correlation
  hwmon4/fan1_input ... speed was 1298 now 57
    It appears that fan hwmon4/fan1_input
    is controlled by pwm hwmon4/pwm1
Would you like to generate a detailed correlation (y)?
Would you like to generate a graphical plot using gnuplot (y)?
    PWM 255 FAN 1292
    PWM 240 FAN 1253
    PWM 225 FAN 1209
    PWM 210 FAN 1161
    PWM 195 FAN 1111
    PWM 180 FAN 1063
    PWM 165 FAN 1012
    PWM 150 FAN 951
    PWM 135 FAN 872
    PWM 120 FAN 800
    PWM 105 FAN 729
    PWM 90 FAN 718
    PWM 75 FAN 718
    PWM 60 FAN 717
    PWM 45 FAN 718
    PWM 30 FAN 719
    PWM 28 FAN 720
    PWM 26 FAN 721
    PWM 24 FAN 718
    PWM 22 FAN 719
    PWM 20 FAN 722
    PWM 18 FAN 723
    PWM 16 FAN 722
    PWM 14 FAN 722
    PWM 12 FAN 721
    PWM 10 FAN 721
    PWM 8 FAN 723
    PWM 6 FAN 723
    PWM 4 FAN 723
    PWM 2 FAN 725
    PWM 0 FAN 285
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
    Hit return to continue...

  hwmon4/fan2_input ... speed was 1286 now 1279
    no correlation
  hwmon4/fan3_input ... speed was 1311 now 1327
    no correlation
  hwmon4/fan4_input ... speed was 1568 now 1534
    no correlation
  hwmon4/fan5_input ... speed was 1216 now 1217
    no correlation

Testing pwm control hwmon4/pwm2 ...
  hwmon3/fan2_input ... speed was 1719 now 1888
    no correlation
  hwmon4/fan1_input ... speed was 1298 now 1288
    no correlation
  hwmon4/fan2_input ... speed was 1286 now 60
    It appears that fan hwmon4/fan2_input
    is controlled by pwm hwmon4/pwm2
Would you like to generate a detailed correlation (y)?
Would you like to generate a graphical plot using gnuplot (y)?
    PWM 255 FAN 1290
    PWM 240 FAN 1249
    PWM 225 FAN 1206
    PWM 210 FAN 1160
    PWM 195 FAN 1115
    PWM 180 FAN 1075
    PWM 165 FAN 1025
    PWM 150 FAN 966
    PWM 135 FAN 898
    PWM 120 FAN 821
    PWM 105 FAN 749
    PWM 90 FAN 735
    PWM 75 FAN 734
    PWM 60 FAN 735
    PWM 45 FAN 736
    PWM 30 FAN 738
    PWM 28 FAN 737
    PWM 26 FAN 739
    PWM 24 FAN 736
    PWM 22 FAN 737
    PWM 20 FAN 739
    PWM 18 FAN 741
    PWM 16 FAN 741
    PWM 14 FAN 741
    PWM 12 FAN 742
    PWM 10 FAN 743
    PWM 8 FAN 741
    PWM 6 FAN 743
    PWM 4 FAN 743
    PWM 2 FAN 744
    PWM 0 FAN 303
    
```
 EDIT: 
    running `fancontrol` afterwards gives this
  
  ```
 fancontrol
Loading configuration from /etc/fancontrol ...

Common settings:
  INTERVAL=10
Error in configuration file (hwmon4/pwm1):
MINSTOP must be less than MAXPWM
```

**Comment by MisterZ42** [comment] 2022-05-07 13:05
I would suggest taking a look at /etc/fancontrol?
But this should not be an issue with the driver.

**Closed as completed by MisterZ42** 2022-05-07 13:05 UTC

**Comment by zany130** [comment] 2022-05-07 20:53
After a while of using hidraw hack branch driver i seem to have bricked my commander pro. Launched into windows and it said it can't detect it's firmware and it needed to be updated so i update it and 8t gets stuck at 99% @MisterZ42

**Comment by MisterZ42** [comment] 2022-05-07 21:20
Should not be because of this hack. (It just interferes with the Effects Plugin, but will not send additional data to the device)
You can factory reset the device. Please google it.
Please be advised, that the hack version is "dirty". Maybe I should add a disclaimer to the README.

**Comment by zany130** [comment] 2022-05-12 15:38
was able to factory restore the device.
but after a recent kernel update to `5.17.6-257`
i get this
```
insmod: ERROR: could not insert module /home/zany130/Documents/GitHub/corsair-cpro/corsair-cpro.ko: Invalid module format
```

**Comment by MisterZ42** [comment] 2022-05-12 15:42
Because it is compiled for a different kernel version.

**Comment by zany130** [comment] 2024-08-06 19:12
Wanted to revisit this as I am getting the same issue when in coolerctrl https://gitlab.com/coolercontrol/coolercontrol/-/issues/327

Is the hidraw_yield branch the same as the old  hack branch @MisterZ42 

I want to try maybe making a dkms module out of it...

**Comment by MisterZ42** [comment] 2024-08-06 19:35
The hidraw_yield branch is a bit more safe than the old hack. Here the driver will yield to hidraw (in your case, the effects plugin) This means, it will not output any data, while the hidraw device is open. I took the hack branch down, because it had issues and I didn't want to cause problems for any users.
This whole thing can only be solved, if just one driver is speaking to the device. In your case, there are two: openRGB and this one. (I am not sure, but I think using liquidctl as a backend for coolercontrol will lead to the exact same problem, while the effects plugin is running)
Since kernel 6.10 there is also a bit more safety in the driver, which should minimize the impact somewhat, but it will not go away completely.
The issue could only be solved on my side, if there was a RGB-API in the kernel. But it does not exist. Sorry.

**Comment by MisterZ42** [comment] 2024-08-06 19:44
PS.: After more thoroughly reading the thread in the coolercontrol issues: If you control the RGB and fans only through coolercontrol and they use only one backend (liquidctl) it will solve the problem.
